name: Build and Export Multi-arch Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/github/workflow/Dockerfile # 请确保此路径准确
          platforms: linux/amd64,linux/arm64
          push: false # 关键：不推送到仓库
          outputs: type=docker,dest=/tmp/image.tar # 关键修改：使用 type=docker 并指定单一文件路径
          tags: ghcr.io/wuhins/n.e.k.o:latest # 为构建指定一个标签
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-amd64-arm64
          path: /tmp/image.tar
          retention-days: 14
